// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gmrknvqgmyzgpvvtowmb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdtcmtudnFnbXl6Z3B2dnRvd21iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzMzgxNjgsImV4cCI6MjA2NDkxNDE2OH0.ZPl1e4qJoHaHNjpPqT8uVGm1JSsHn1fbwjczpPF_1Bg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);